name: OnboardingApp
options:
  bundleIdPrefix: com.aamad
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "14.3"

targets:
  OnboardingApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: OnboardingApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aamad.OnboardingApp
      SWIFT_VERSION: "5.7"
      TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
      INFOPLIST_FILE: OnboardingApp/Info.plist
    info:
      path: OnboardingApp/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: Onboarding App
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  OnboardingAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: OnboardingAppTests
    dependencies:
      - target: OnboardingApp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.aamad.OnboardingAppTests
      SWIFT_VERSION: "5.7"
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/OnboardingApp.app/OnboardingApp

schemes:
  OnboardingApp:
    build:
      targets:
        OnboardingApp: all
    test:
      targets:
        - OnboardingAppTests
    run:
      config: Debug

